name:
description:

inputs:
  VITE_API_KEY:
    description: Firebase api key
    required: true
  VITE_AUTH_DOMAIN:
    description: Firebase auth domain
    required: true
  VITE_PROJECT_ID:
    description: Firebase project id
    required: true
  VITE_STORAGE_BUCKET:
    description: Firebase storage bucket
    required: true
  VITE_MESSAGING_SENDER_ID:
    description: Firebase messaging sender id
    required: true
  VITE_APP_ID:
    description: Firebase app it
    required: true
  VITE_MEASUREMENT_ID:
    description: Firebase measurement id
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout Repo
      uses: actions/checkout@main

    - name: Setup Node.js (NPM)
      uses: actions/setup-node@master
      with:
        node-version: "18.x"

    # - name: Use cached node_modules
    #   uses: actions/cache@master
    #   with:
    #     path: node_modules
    #     key: nodeModules-${{ hashFiles('**/yarn.lock') }}
    #     restore-keys: |
    #       nodeModules-

    - name: Install dependencies
      shell: bash
      run: npm install
      env:
        CI: true

    - name: Build Development
      shell: bash
      env:
        VITE_API_KEY: ${{inputs.VITE_API_KEY}}
        VITE_AUTH_DOMAIN: ${{inputs.VITE_AUTH_DOMAIN}}
        VITE_PROJECT_ID: ${{inputs.VITE_PROJECT_ID}}
        VITE_STORAGE_BUCKET: ${{inputs.VITE_STORAGE_BUCKET}}
        VITE_MESSAGING_SENDER_ID: ${{inputs.VITE_MESSAGING_SENDER_ID}}
        VITE_APP_ID: ${{inputs.VITE_APP_ID}}
        VITE_MEASUREMENT_ID: ${{inputs.VITE_MEASUREMENT_ID}}
      run: |
        echo "VITE_API_KEY=$VITE_API_KEY
        VITE_AUTH_DOMAIN=$VITE_AUTH_DOMAIN
        VITE_PROJECT_ID=$VITE_PROJECT_ID
        VITE_STORAGE_BUCKET=$VITE_STORAGE_BUCKET
        VITE_MESSAGING_SENDER_ID=$VITE_MESSAGING_SENDER_ID
        VITE_APP_ID=$VITE_APP_ID
        VITE_MEASUREMENT_ID=$VITE_MEASUREMENT_ID" >> .env
        npm run build

    - name: Archive Production Artifact
      uses: actions/upload-artifact@main
      with:
        name: build
        path: dist
