name: action
description:

inputs:
  VITE_API_KEY:
    description: Firebase api key
    required: true
  VITE_AUTH_DOMAIN:
    description: Firebase auth domain
    required: true
  VITE_PROJECT_ID:
    description: Firebase project id
    required: true
  VITE_STORAGE_BUCKET:
    description: Firebase storage bucket
    required: true
  VITE_MESSAGING_SENDER_ID:
    description: Firebase messaging sender id
    required: true
  VITE_APP_ID:
    description: Firebase app it
    required: true
  VITE_MEASUREMENT_ID:
    description: Firebase measurement id
    required: true
  DB_HOST:
    description: Database ip address
    required: true
  DB_PORT:
    description: Database port
    required: true
  DB_USERNAME:
    description: Database username
    required: true
  DB_PASSWORD:
    description: Database password
    required: true
  DB_DATABASE:
    description: Database database
    required: true
  TMDB_API_KEY:
    description: TMDB api key
    required: true
  VITE_SERVER_URL:
    description: Backend server url
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout Repo
      uses: actions/checkout@main

    - name: Setup Node.js (NPM)
      uses: actions/setup-node@master
      with:
        node-version: "18.x"

    - name: Install dependencies
      shell: bash
      run: npm install
      env:
        CI: true

    - name: Build Development
      shell: bash
      env:
        VITE_API_KEY: ${{inputs.VITE_API_KEY}}
        VITE_AUTH_DOMAIN: ${{inputs.VITE_AUTH_DOMAIN}}
        VITE_PROJECT_ID: ${{inputs.VITE_PROJECT_ID}}
        VITE_STORAGE_BUCKET: ${{inputs.VITE_STORAGE_BUCKET}}
        VITE_MESSAGING_SENDER_ID: ${{inputs.VITE_MESSAGING_SENDER_ID}}
        VITE_APP_ID: ${{inputs.VITE_APP_ID}}
        VITE_MEASUREMENT_ID: ${{inputs.VITE_MEASUREMENT_ID}}
        DB_HOST: ${{inputs.DB_HOST}}
        DB_PORT: ${{inputs.DB_PORT}}
        DB_USERNAME: ${{inputs.DB_USERNAME}}
        DB_PASSWORD: ${{inputs.DB_PASSWORD}}
        DB_DATABASE: ${{inputs.DB_DATABASE}}
        TMDB_API_KEY: ${{inputs.TMDB_API_KEY}}
        VITE_SERVER_URL: ${{inputs.VITE_SERVER_URL}}
      run: |
        echo "VITE_API_KEY=$VITE_API_KEY
        VITE_AUTH_DOMAIN=$VITE_AUTH_DOMAIN
        VITE_PROJECT_ID=$VITE_PROJECT_ID
        VITE_STORAGE_BUCKET=$VITE_STORAGE_BUCKET
        VITE_MESSAGING_SENDER_ID=$VITE_MESSAGING_SENDER_ID
        VITE_APP_ID=$VITE_APP_ID
        VITE_MEASUREMENT_ID=$VITE_MEASUREMENT_ID
        VITE_DB_HOST=$DB_HOST
        VITE_DB_PORT=$DB_PORT
        VITE_DB_USERNAME=$DB_USERNAME
        VITE_DB_PASSWORD=$DB_PASSWORD
        VITE_DB_DATABASE=$DB_DATABASE
        VITE_TMDB_API_KEY=$TMDB_API_KEY
        VITE_SERVER_URL=$VITE_SERVER_URL" >> .env
        npm run build

    - name: Archive Production Artifact
      uses: actions/upload-artifact@main
      with:
        name: build
        path: dist
