FROM node:18.8.0-alpine3.16 as build

WORKDIR /app

COPY . ./

# ---
FROM arm64v8/nginx

WORKDIR /etc/nginx
ADD ./.docker/nginx-arm.conf /etc/nginx/nginx.conf

COPY --from=build ./app/dist /usr/share/nginx/html
EXPOSE 5173
CMD ["nginx", "-g", "daemon off;"]